---
# skip jinja testing
- name: Get user info for "{{ ansible_user_id }}"
  ansible.builtin.user:
    user: "{{ ansible_user_id }}"
    state: present
  register: user_info

- name: Normalize default paths
  ansible.builtin.set_fact:
    readarr_config_path: "{{ readarr_config_path | replace('~', user_info.home) }}"
    readarr_data_path: "{{ readarr_data_path | replace('~', user_info.home) }}"

- name: Create directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: "0750"
    recurse: true
  loop:
    - "{{ readarr_config_path }}"
    - "{{ readarr_data_path }}"

- name: Put container related files on the host
  ansible.builtin.template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: "0640"
  loop:
    - { src: readarr.container.j2, dest: "{{ user_info.home }}/.config/containers/systemd/readarr.container" }

- name: Start the container service
  ansible.builtin.systemd:
    name: readarr
    state: started
    scope: user
    enabled: true
    daemon_reload: true
