---
role_name_check: 1
driver:
  name: podman
platforms:
  - name: readarr_develop
    image: quay.io/speakintelnet/pinp-molecule
    privileged: true
    pre_build_image: true
    systemd: true
  - name: readarr_nightly
    image: quay.io/speakintelnet/pinp-molecule
    privileged: true
    pre_build_image: true
    systemd: true
provisioner:
  name: ansible
  inventory:
    host_vars:
      readarr_develop:
        ansible_user: podman
        readarr_version: develop
      readarr_nightly:
        ansible_user: podman
        readarr_version: nightly
verifier:
  name: ansible
